### ISSUE TITLE
It doesn't see imports in <script setup>

### ISSUE THREAD

**Issue by idmytro** [tkskto/vue-component-analyzer#240]
I have some files with `<script setup lang="ts">` and vca v.0.6.1 can't analyze them

**Comment by tkskto** [comment]
Thank you for your issue. I'll try to fix this within the year 🙏

**Comment by idmytro** [comment]
wow thank you
I tried to change some lines of code, but I failed

**Comment by tkskto** [comment]
@idmytro I published v0.7.0, and this issue should be solved. Could you please try it out?

**Comment by idmytro** [comment]
> @idmytro I published v0.7.0, and this issue should be solved. Could you please try it out?

thank you I will try

**Comment by idmytro** [comment]
It works!

**Comment by tkskto** [comment]
Thanks!
