### ISSUE TITLE
Support tsconfig path aliases

### ISSUE THREAD

**Issue by hinogi** [tkskto/vue-component-analyzer#309]
It seems that in the case of script setup with typescript the tsconfig is not read and imports via ts path aliases are not found.

**Comment by tkskto** [comment]
@hinogi I'm really sorry for the delay in responding to your issue.

I published [v0.9.0](https://github.com/tkskto/vue-component-analyzer/releases/tag/v0.9.0), and this issue should be solved. If not, please let me know again🙏

**Comment by hinogi** [comment]
I will try again when I am back at work.
Your effort is highly appreciated, I can always wait for OSS ppl

**Comment by hinogi** [comment]
> @hinogi I'm really sorry for the delay in responding to your issue.
> 
> I published [v0.9.0](https://github.com/tkskto/vue-component-analyzer/releases/tag/v0.9.0), and this issue should be solved. If not, please let me know again🙏

btw. maybe you want to also use alias-hq to even make loading something else than `tsconfig.json` in the age of monorepos there and overwhelming tooling ppl tend to have a plethora of tsconfig files like `tsconfig.app.json`, `tsconfig.eslint.json`, `tsconfig.spec.json` and so on. I don't know how get-tsconfig works but if it is already supported then all is right.

**Comment by sschneider-ihre-pvs** [comment]
works great !
